### ISSUE TITLE
http PUT Method Not Allowed on the chapter-up-and-running folder

### ISSUE THREAD

**Issue by makersu** [RayRoestenburg/akka-in-action#30]
```
marksu@~/work/githubScala/akka-in-action/chapter-up-and-running$ sbt run
...
marksu@~/work/githubScala/akka-in-action/chapter-up-and-running$ http PUT localhost:5000/events event=RHCP nrOfTickets:=10
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Length: 47
Content-Type: text/plain; charset=UTF-8
Date: Mon, 21 Dec 2015 15:49:45 GMT
Server: GoTicks.com REST API

HTTP method not allowed, supported methods: GET
```

**Comment by RayRoestenburg** [comment]
This is correct, PUT is not used.

See https://github.com/RayRoestenburg/akka-in-action/blob/master/chapter-up-and-running/src/main/scala/com/goticks/RestApi.scala#L31-L91

**Comment by rschiavi** [comment]
the book says use a PUT. how does one add tickets? POST doesn't seem to work either. 
http POST localhost:5000/events event=DjMadlib nrOfTickets:=15

thanks,

**Comment by RayRoestenburg** [comment]
Use 
```
http POST localhost:5000/events/DjMadlib  nrOfTickets:=15
```

(I know,not very standard REST)

**Comment by baiwfg2** [comment]
I use 
> http POST localhost:5000/events/DjMadlib  nrOfTickets:=15
 
but got:

HTTP/1.1 400 Bad Request
Content-Length: 78
Content-Type: text/plain; charset=UTF-8
Date: Tue, 25 Jul 2017 04:33:32 GMT
Server: GoTicks.com REST API

The request content was malformed:
Object is missing required member 'tickets'

**Comment by RayRoestenburg** [comment]
Try

```
http POST localhost:5000/events/DjMadlib tickets:=15
```

(Sorry for the late response)
