### ISSUE TITLE
why frontend RemoteLookupProxy keep sending Identify(path) or receiving ActorIdentity(`path`, None) under chapter-remoting? 

### ISSUE THREAD

**Issue by makersu** [RayRoestenburg/akka-in-action#31]
when there is only frontend up, why it keep sending Identify(path) or receiving ActorIdentity(`path`, None)? 

```
[ERROR] [12/29/2015 17:08:16.054] [frontend-akka.actor.default-dispatcher-4] [akka.tcp://frontend@0.0.0.0:2552/user/restInterface/lookupBoxOffice] Remote actor with path akka.tcp://backend@0.0.0.0:2551/user/boxOffice is not available.
[WARN] [12/29/2015 17:08:19.067] [frontend-akka.actor.default-dispatcher-2] [akka.tcp://frontend@0.0.0.0:2552/user/restInterface/lookupBoxOffice] ???context.actorSelection(path)=ActorSelection[Anchor(akka.tcp://backend@0.0.0.0:2551/), Path(/user/boxOffice)]
[ERROR] [12/29/2015 17:08:19.068] [frontend-akka.actor.default-dispatcher-2] [akka.tcp://frontend@0.0.0.0:2552/user/restInterface/lookupBoxOffice] Remote actor with path akka.tcp://backend@0.0.0.0:2551/user/boxOffice is not available.
```

**Comment by RayRoestenburg** [comment]
Sorry to see this so terribly late. This is on purpose. The `RemoteLookupProxy` tries to identify the actor and switch to an active state so it can forward messages to the actor. It first tries to get an `ActorRef`, by immediately sending an identity request.
`setReceiveTimeout` causes a `ReceiveTimeout` message to be sent to the `RemoteLookupProxy` if it receives no messages. If you look at the code, you will see that an `Identify` request also is sent when the `ReceiveTimeout` is received. Once it receives an `ActorIdentity`, the `RemoteLookupProxy` switches to the active state, until the actor identified by `ActorRef` is terminated, at which point the RemoteLookupProxy will continuously try to identify again.
