### ISSUE TITLE
"git push heroku master" fails for Chapter 2: up and running (Listing 2.29)

### ISSUE THREAD

**Issue by centaure** [RayRoestenburg/akka-in-action#32]
I followed the instructions in section 2.3, and everything works well until I attempt the command in Listing 2.29. For whatever reason, as shown below, the sbt example you gave is being detected as a Play app (default v 1.3.1). Even if I try to use a scala build pack (using `heroku buildpacks:set heroku/scala`), I get a *Push rejected, failed to detect set buildpack heroku/scala* error. I don't have time to debug this, and would like to know if you have a solution? 

     git push heroku master     
     Compressing objects: 100% (1074/1074), done.
     Writing objects: 100% (2585/2585), 384.80 KiB | 0 bytes/s, done.
     Total 2585 (delta 875), reused 2585 (delta 875)
     remote: Compressing source files... done.
     remote: Building source:
     remote: 
     remote: -----> Play! app detected
     remote: -----> Installing OpenJDK 1.6... done
     remote: -----> WARNING: Play! version not specified in dependencies.yml. Default version: 1.3.1 being used....
     remote: -----> Installing Play! 1.3.1.....
     remote: -----> done
     remote: -----> Building Play! application...
     remote:        ~        _            _ 
     remote:        ~  _ __ | | __ _ _  _| |
     remote:        ~ | '_ \| |/ _' | || |_|
     remote:        ~ |  __/|_|\____|\__ (_)
     remote:        ~ |_|            |__/   
     remote:        ~
     remote:        ~ play! 1.3.1, https://www.playframework.com
     remote:        ~
     remote:        1.3.1
     remote:        Building Play! application at directory ./
     remote:        Resolving dependencies: .play/play dependencies ./ --forProd --forceCopy --silent -Duser.home=/tmp/build_2b9abc1199029835e52cc9f7fcd096ed 2>&1
     remote:        ~ !! /tmp/build_2b9abc1199029835e52cc9f7fcd096ed/conf/dependencies.yml does not exist
     remote:  !     Failed to build Play! application
     remote:  !     Cleared Play! framework from cache
     remote: 
     remote:  !     Push rejected, failed to compile Play! app
     remote: 
     remote: Verifying deploy....
     remote: 
     remote: !	Push rejected to fierce-falls-1349.
     remote: 
     To https://git.heroku.com/fierce-falls-1349.git
      ! [remote rejected] master -> master (pre-receive hook declined)
     error: failed to push some refs to 'https://git.heroku.com/fierce-falls-1349.git'

Note that I am running everything on a MAC OS X Yosemite (10.10.5). I installed the heroku toolbelt from the heroku website, and `sbt clean compile stage` goes through with no problems.  In addition, I could create a heroku app using the example [here](https://github.com/kissaten/sbt-minimal-scala-sample) (i.e. `git push heroku master` for this example ran without problems).

`heroku --version` gives the following output:

     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
     heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2
     === Installed Plugins
     heroku-apps@1.0.0
     heroku-cli-addons@0.1.1
     heroku-fork@4.0.0
     heroku-git@2.4.4
     heroku-local@4.1.5
     heroku-run@2.9.2
     heroku-status@1.2.4

**Comment by centaure** [comment]
I believe I have figured out the problem. A .git folder needs to be initialized in chapter-up-and-running subfolder?

Particularly, I realized that if I follow the following steps (as per the book instructions): 
1. clone the repo as instructed in Listing 2.1 (i.e. git clone https://github.com/RayRoestenburg/akka-in-action.git),
2. perform the heroku toolbelt install, 
3. create the app in heroku from the chapter-up-and-running directory as instructed in Listing 2.25 (i.e. heroku create, which also adds the remote "heroku"), and,
4. push into heroku as instructed in Listing 2.29 (i.e. git push heroku),

I will get the above behavior, where for some reason a Play v1.3.1 app is detected.

However, if I run the following commands between items 2 and 3 above:

     git init
     git add ./
     git commit -m "Initial commit"

then everything works fine when I run items 3 followed by 4 (i.e. a Scala app is detected). Part of the output after running item 4 (git push heroku master) is as follows:

     git push heroku master
     Counting objects: 29, done.
     Delta compression using up to 8 threads.
     Compressing objects: 100% (22/22), done.
     Writing objects: 100% (29/29), 8.04 KiB | 0 bytes/s, done.
     Total 29 (delta 0), reused 0 (delta 0)
     remote: Compressing source files... done.
     remote: Building source:
     remote: 
     remote: -----> Scala app detected
     remote: -----> Installing OpenJDK 1.8... done
     remote: -----> Priming Ivy cache... done
     remote: -----> Running: sbt compile stage
     remote: Downloading sbt launcher for 0.13.7:
     remote:   From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar
     remote:     To  /tmp/scala_buildpack_build_dir/.sbt_home/launchers/0.13.7/sbt-launch.jar
     remote:        Getting org.scala-sbt sbt 0.13.7 ...
     remote:        downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.7/jars/sbt.jar ...
     remote:        	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.7!sbt.jar (336ms)
     |
     |
     |
     |
     |
     remote:        [info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar ...
     remote:        [info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.1!scala-reflect.jar (165ms)
     remote:        [info] Done updating.
     remote:        [info] Compiling 5 Scala sources to /tmp/scala_buildpack_build_dir/target/scala-2.11/classes...
     remote:        [info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
     remote:        [info]   Compilation completed in 16.171 s
     remote:        [success] Total time: 29 s, completed Jan 4, 2016 1:10:30 AM
     remote:        [info] Wrote /tmp/scala_buildpack_build_dir/target/scala-2.11/goticks_2.11-1.0.pom
     remote:        [info] Packaging /tmp/scala_buildpack_build_dir/target/scala-2.11/goticks_2.11-1.0.jar ...
     remote:        [info] Done packaging.
     remote:        [success] Total time: 1 s, completed Jan 4, 2016 1:10:30 AM
     remote: -----> Dropping ivy cache from the slug
     remote: -----> Dropping sbt boot dir from the slug
     remote: -----> Dropping compilation artifacts from the slug
     remote: -----> Discovering process types
     remote:        Procfile declares types -> web
     remote: 
     remote: -----> Compressing... done, 63.7MB
     remote: -----> Launching... done, v5
     remote:        https://nameless-scrubland-9492.herokuapp.com/ deployed to Herok
     remote: 
     remote: Verifying deploy.... done.
     To https://git.heroku.com/nameless-scrubland-9492.git
      * [new branch]      master -> master

**Comment by RayRoestenburg** [comment]
Thanks @centaure. Did you also read this? https://github.com/RayRoestenburg/akka-in-action/tree/master/chapter-up-and-running 
Did you do the `git subtree push` command as well?

**Comment by centaure** [comment]
Hey Roy, thanks for your prompt reply. I tried out the `git subtree push` command (given in the Note) before running Listing 2.29, and everything works as expected. 
I did not read the Note earlier, as I was following the book as it was structured.  In other words I was working on your instruction 
*After that, push the code to Heroku with the following command* 
i.e. I expected Listing 2.29 to work, since there was no reference to the Note at this point. Had I seen the relation between the Note and Listing 2.29 when I read the above instruction, it would have saved me a lot of time. Maybe you should indicate to the reader that he/she should read the Note before running Listing 2.29? Just a suggestion.

Sunil

**Comment by RayRoestenburg** [comment]
Sounds like a good idea, thanks Sunil.

**Comment by centaure** [comment]
Thanks Roy. And thanks to you and the other authors for putting this book together. It has definitely provided me with more (very helpful) insight into Akka.

**Comment by RayRoestenburg** [comment]
Your welcome.
