### ISSUE TITLE
Spray dependency

### ISSUE THREAD

**Issue by rutaihwa** [RayRoestenburg/akka-in-action#36]
Hi @RayRoestenburg I've started the book yesterday and I find it great. Great work. In chapter-up-and-running, template [build.sbt](https://github.com/RayRoestenburg/akka-in-action/blob/master/chapter-up-and-running/build.sbt#L16), we still have a dependence for spray-json are there some stuff we still don't have in akka-http-spray-json-experimental? And if that so should we have back the spray-repo in dependecy resolution? Thanks :smile:

**Comment by RayRoestenburg** [comment]
Hi @rutaihwa great you like it, I'll check, since akka-http-spray-json-experimental should probably pull in spray-json transitively, but not sure. Did everything build for you without the spray-repo dependency, or did it fail?

**Comment by rutaihwa** [comment]
Without the spray-repo dependency build fails to resolve spray-json.  But without spray-json, it still built fine and spray.json can still be imported in the project.

**Comment by RayRoestenburg** [comment]
Ok thanks, I'll remove the dependency.

**Comment by rutaihwa** [comment]
:+1: Great!
