### ISSUE TITLE
"chapter-persistence" - PersistentView is deprecated

### ISSUE THREAD

**Issue by BranislavLazic** [RayRoestenburg/akka-in-action#42]
In [CalculatorHistory](https://github.com/RayRoestenburg/akka-in-action/blob/master/chapter-persistence/src/main/scala/aia/persistence/calculator/CalculatorHistory.scala) you are using PersistentView to track message stream. In Akka 2.4 recommended way is to use Persistence Query.

**Comment by RayRoestenburg** [comment]
Correct will be updated very soon
