### ISSUE TITLE
dag

### ISSUE THREAD

**Issue by tlw-ray** [RayRoestenburg/akka-in-action#44]
In chapter-stream graph.run() need implicit Materializer, but ActorMaterializer is not a akka.stream.Materializer in akka2.4.9。

Error:(39, 20) could not find implicit value for parameter materializer: akka.stream.Materializer
  runnableGraph.run().foreach{ result =>

But your

Source like these:

----------------------------------------------------------------

aia.stream.GenerateLogFile.scala

implicit val materializer = ActorMaterializer() //ActorMaterializer is not a akka.stream.Materializer
graph.run().foreach { result =>
... ...
----------------------------------------------------------------

akka.stream.scaladsl.Flow

//graph.run()(implicit materializer: Materializer) ...
def run()(implicit materializer: Materializer): Mat = materializer.materialize(this)
... ...
----------------------------------------------------------------

akka.stream.ActorMaterializer

object ActorMaterializer {
... ...
----------------------------------------------------------------

**Comment by RayRoestenburg** [comment]
Please look at abstract class ActorMaterializer it is a Materializer.

**Comment by RayRoestenburg** [comment]
Also cant get to laptop right now to check.

**Comment by tlw-ray** [comment]
Thanks~!
