### ISSUE TITLE
comments in code

### ISSUE THREAD

**Issue by semephor** [RayRoestenburg/akka-in-action#45]
Hello, in the code examples (for example chapter 2), why is the code littered with comments such as:
 
<start id='"ch02_event_route'

Is there any reason for this? It is quite confusing when trying to understand the code, especially to a Scala beginner. Thanks.

**Comment by RayRoestenburg** [comment]
This is there since we used the exact code to generate the book, the code is processed by an internal tool at Manning for annotating code in the book. since the book is finished now, these could be removed.
