### ISSUE TITLE
why does it not unwatch an actor in Fault Tolerance chapter?

### ISSUE THREAD

**Issue by weicheng113** [RayRoestenburg/akka-in-action#51]
Hi guys,

I am confused with the code in [Fault Tolerance example](https://github.com/RayRoestenburg/akka-in-action/blob/master/chapter-fault-tolerance/src/main/scala/aia/faulttolerance/LogProcessing1.scala#L57), when it watches a fileWatcher actor(line 57 context.watch(fileWatcher)), but it does not unwatch it when one of them is terminated.

Do we usually unwatch an actor when it is terminated? does it have any consequence if we don't unwatch?

Thanks in advance,
Cheng

**Comment by RayRoestenburg** [comment]
It has no real consequence if you do not unwatch, unless you watch huge
numbers of actors. The docs do say you should unwatch when the actor is
terminated, so it is probably the most clean thing to do.

**Comment by weicheng113** [comment]
Thanks for the explanation, Raymond.
