### ISSUE TITLE
Put the project dependency settings into the ROOT/build.sbt

### ISSUE THREAD

**Issue by WillemJiang** [RayRoestenburg/akka-in-action#55]
It's hard for us to upgrade the version of Akka or some other third party library if we don't manage the dependencies from the ROOT/build.sbt.
My suggestion is we can put all the project settings into the ROOT/build.sbt to avoid change the version per project/build.sbt.

**Comment by RayRoestenburg** [comment]
Since these build files are examples per chapter, I prefer to leave it the way it is, even it that means more changes across the projects. I think it is more valuable that a reader can just jump into a self-contained build file for a chapter and not have to worry how multi-project sbt files work.
