### ISSUE TITLE
Please post code for 5.5 (Futures in Actors)

### ISSUE THREAD

**Issue by lukewyman** [RayRoestenburg/akka-in-action#59]
The book has a snippet for explaining using Futures inside Actors. Any chance the full source of that is available to be posted here?

Thanks :)

**Comment by RayRoestenburg** [comment]
You should be able to find it in the directory for chapter 2 (chapter-up-and-running) in BoxOffice.scala, if you are referring to Listing 5.26, is that the one you mean?

**Comment by lukewyman** [comment]
Yup, that would be it. Closing this out. Thanks!
