### ISSUE TITLE
[ch3 testdriven] expectMsg instead of expectMsgPF for SortedEvents

### ISSUE THREAD

**Issue by wojtasskorcz** [RayRoestenburg/akka-in-action#60]
In chapter 3 on page 57 we implement `SendingActor` and test it. The test uses `expectMsgPF` because, as the book explains it:
"Since the SortEvents message contains a random vector of events, we can’t use an expectMsg(msg); we can’t formulate an exact match for it. In this case we use expectMsgPF , which takes a partial function just like the receive of the actor."

I replaced 

    expectMsgPF() {
      case SortedEvents(events) =>
        events.size must be(size)
        unsorted.sortBy(_.id) must be(events)
    }

with

    expectMsg(SortedEvents(unsorted.sortBy(_.id)))

and it seems to work properly. Why is it not the optimal solution?

**Comment by RayRoestenburg** [comment]
It is the optimal solution. The example is somewhat contrived to show
expectMsgPF

**Comment by wojtasskorcz** [comment]
Ah, cool! Thanks for the quick response Ray!

**Comment by RayRoestenburg** [comment]
No problem
