### ISSUE TITLE
Developing the Futures w/ Actors idea further...

### ISSUE THREAD

**Issue by lukewyman** [RayRoestenburg/akka-in-action#62]
Hey @RayRoestenburg - I've been working on understanding Chapter 5 - Futures (hybridized with some Chapter 2 - Up and Running stuff) and came up with something that I like in a portfolio project I'm working on. You can check out my actor that works with Futures [here](https://github.com/lukewyman/ecommerce/blob/master/orchestrator/src/main/scala/com/ecommerce/orchestrator/backend/actor/orchestrator/ShoppingOrchestrator.scala).

- Essentially I made an "orchestrator" actor that coordinates ask(?)'s to several HttpClient actors. Each HttpClient actor hits a microservice and returns a result accordingly. So to checkout after shopping, you'd want to coordinate requests to the _payment_, _inventory_, and _shoppingcart_ microservices.
- HttpClient actors return a `Future[Either[SomeResponse]]`. The `Left` has an error that captures what might have gone wrong when the HttpClient hit the microservice
- I also borrowed the separate trait idea from `BoxOfficeApi` from Chapter 2 - Up and Running to abstract away the ask-y future-y stuff, and mixed that into the orchestrator actor
- `Future[Either[SomeResponse]]` is a hassle, so I used the `EitherT` monad transformer from [cats](https://github.com/typelevel/cats) to make nice `flatMapF` calls and `for` comprehensions.
- so  I think this is a pattern that brings it all together for a nice, clean way of getting something like this done.
- (I  still haven't put in logic to kill the children and self after the request is done, but anyway)

Also, if there's a way I can simplify it down and adapt it to your TicketInfo example, I'd be happy to do a PR on this repo that builds a TicketInfo with calls to client actors that hit the webservices you refer to.

**Comment by RayRoestenburg** [comment]
Hi Luke, 

Sounds like you've been able to build on top of the examples to good use!  (The link to your orchestrator actor does not work, so I could not look at the details).

Since these are the examples for the book, I prefer to keep them as is (also saves me from having to explain monad transformers in an updated version of the book ;-) but feel free to publish a more built out version of the example somewhere and refer to that repo to the one here.

Cheers,
Ray
