### ISSUE TITLE
How It find that two woker nodes are up Not sure if this is correct as without even single worker i see master node is ready message

### ISSUE THREAD

**Issue by ashishsoni** [RayRoestenburg/akka-in-action#65]
if(roles.contains("master")) {
    Cluster(system).registerOnMemberUp {
      val receptionist = system.actorOf(Props[JobReceptionist],
        "receptionist")
      println("Master node is ready.")

**Comment by RayRoestenburg** [comment]
The minimum master nodes is one, so if that is up, the cluster will be up. There was an issue before with minimum number of nodes, I don't have time right now to look into it though, maybe later next week.
(Maybe try to change the min-nr-of-members in the config)

**Comment by lewapek** [comment]
Hi,
I think I know how to solve this issue. Please, have a look at PR (https://github.com/RayRoestenburg/akka-in-action/pull/87).

@ashishsoni 
I assumed, you were running 4 nodes (1 node with seed.conf, 1 node with master.conf, 2 nodes with worker.conf).
And after seed and master nodes were up (workers not running yet) you saw "Master node is ready." message on the master node but proper behavior is to print this message only when the remaining worker nodes are up. If so - the issue should now be fixed. I tested it and "Master node is ready." appears only after 2nd worker node is up.
