### ISSUE TITLE
Chapter remoting: Frontend can't deploy backend

### ISSUE THREAD

**Issue by mb720** [RayRoestenburg/akka-in-action#67]
Hi and thanks a lot for your book!

When I `sbt run com.goticks.FrontendRemoteDeployWatchMain` (without starting the backend node first) and send an HTTP request to the app (e.g., `curl -s http://localhost:5000/events`), I get this: 

> [info] Running com.goticks.FrontendRemoteDeployWatchMain
> [DEBUG] [04/22/2017 15:06:13.201] [run-main-0] [EventStream] StandardOutLogger started
> INFO  [Slf4jLogger]: Slf4jLogger started
> [DEBUG] [04/22/2017 15:06:13.704] [run-main-0] [EventStream(akka://frontend)] logger log1-Slf4jLogger started
> [DEBUG] [04/22/2017 15:06:13.705] [run-main-0] [EventStream(akka://frontend)] Default Loggers started
> INFO  [Remoting]: Starting remoting
> INFO  [Remoting]: Remoting started; listening on addresses :[akka.tcp://frontend@0.0.0.0:2552]
> INFO  [Remoting]: Remoting now listens on addresses: [akka.tcp://frontend@0.0.0.0:2552]
> INFO  [go-ticks]: RestApi bound to /0:0:0:0:0:0:0:0:5000
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> WARN  [ReliableDeliverySupervisor]: Association with remote system [akka.tcp://backend@0.0.0.0:2551] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://backend@0.0.0.0:2551]] Caused by: [Connection refused: no further information: /0.0.0.0:2551]
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRef]: Message [akka.remote.DaemonMsgCreate] from Actor[akka://frontend/deadLetters] to Actor[akka.tcp://backend@0.0.0.0:2551/remote] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRef]: Message [com.goticks.BoxOffice$GetEvents$] from Actor[akka://frontend/temp/$a] to Actor[akka.tcp://backend@0.0.0.0:2551/remote/akka.tcp/frontend@0.0.0.0:2552/user/forwarder/boxOffice#-900370488] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [8] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> WARN  [ReliableDeliverySupervisor]: Association with remote system [akka.tcp://backend@0.0.0.0:2551] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://backend@0.0.0.0:2551]] Caused by: [Connection refused: no further information: /0.0.0.0:2551]
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [9] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteActorRefProvider$RemoteDeadLetterActorRef]: Message [akka.remote.RemoteWatcher$Heartbeat$] from Actor[akka://frontend/system/remote-watcher#801800298] to Actor[akka://frontend/deadLetters] was not delivered. [10] dead letters encountered, no more dead letters will be logged. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> INFO  [RemoteBoxOfficeForwarder]: Actor $actorRef terminated.
> INFO  [RemoteBoxOfficeForwarder]: switching to deploying state
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> INFO  [RemoteBoxOfficeForwarder]: Actor $actorRef terminated.
> INFO  [RemoteBoxOfficeForwarder]: switching to deploying state
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> INFO  [RemoteBoxOfficeForwarder]: Actor $actorRef terminated.
> INFO  [RemoteBoxOfficeForwarder]: switching to deploying state
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> INFO  [RemoteBoxOfficeForwarder]: Actor $actorRef terminated.
> INFO  [RemoteBoxOfficeForwarder]: switching to deploying state
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> INFO  [RemoteBoxOfficeForwarder]: Actor $actorRef terminated.
> INFO  [RemoteBoxOfficeForwarder]: switching to deploying state
> INFO  [RemoteBoxOfficeForwarder]: switching to maybe active state
> // A lot of the above...
> ERROR [ActorSystemImpl]: Error during processing of request: 'Ask timed out on [Actor[akka://frontend/user/forwarder#204738603]] after [20000 ms]. Sender[null] sent message of type "com.goticks.BoxOffice$GetEvents$".'. Completing with 500 Internal Server Error response.
> WARN  [ReliableDeliverySupervisor]: Association with remote system [akka.tcp://backend@0.0.0.0:2551] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://backend@0.0.0.0:2551]] Caused by: [Connection refused: no further information: /0.0.0.0:2551]

I was under the impression that the frontend could create the backend on demand.

Thanks for your help!

**Comment by RayRoestenburg** [comment]
You need to start the backend, remote deployment requires at least a remote
actor system running.
