### ISSUE TITLE
addSbtPlugin("com.typesafe.sbt" % "sbt-start-script" % "0.10.0")

### ISSUE THREAD

**Issue by epiphyllum** [RayRoestenburg/akka-in-action#69]
sbt update failed for this plugin

**Comment by RayRoestenburg** [comment]
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-start-script/scala_2.10/sbt_0.13/0.10.0/jars/sbt-start-script.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.sbt#sbt-start-script;0.10.0!sbt-start-script.jar (1673ms)

Works ok for me as well, maybe try to start with a clean sbt setup, clean ivy repo. (Also, these kind of issues can be intermittent, so please try again)
