### ISSUE TITLE
Error: Could not find or load main class com.goticks.SingleNodeMain

### ISSUE THREAD

**Issue by AmineSagaama** [RayRoestenburg/akka-in-action#74]
In the second chapter / Listing 2.2   Running the JAR : When I execute the command : java -jar target/scala-2.11/goticks-assembly-1.0.jar   I got this exception : Error: Could not find or load main class com.goticks.SingleNodeMain

**Comment by RayRoestenburg** [comment]
Should be fixed now, in master,
