### ISSUE TITLE
java.lang.RuntimeException: No main class detected.

### ISSUE THREAD

**Issue by dmilan77** [RayRoestenburg/akka-in-action#75]
When I run `opt/workspace/IdeaProjects/akka-in-action$ sbt run` or `opt/workspace/IdeaProjects/akka-in-action$ java -jar target/scala-2.10/all-assembly-1.0.jar `
I get **No main class detected.**
I am running it from root directory.

**Comment by RayRoestenburg** [comment]
You need to choose one of the sub projects (sbt projects), for instance:
```
sbt
projects
project up
run
```

or 
`sbt 'project up' run` for instance.
