### ISSUE TITLE
PUT method not supported ?

### ISSUE THREAD

**Issue by baiwfg2** [RayRoestenburg/akka-in-action#76]
Hi, Raymond. I'm learning chapter 6 about akka remoting. When i used httpie to test the GoTick app

http put localhost:5000/events event=RHCP nrOfTickets:=10

> HTTP/1.1 405 Method Not Allowed
> Allow: GET
> Content-Length: 47
> Content-Type: text/plain; charset=UTF-8
> Date: Wed, 19 Jul 2017 07:34:26 GMT
> Server: GoTicks.com REST API
> 
> HTTP method not allowed, supported methods: GET

why is that ? I check the source code and didn't see PUT but POST. But it's still the problem

**Comment by RayRoestenburg** [comment]
Hi, please see https://github.com/RayRoestenburg/akka-in-action/issues/30
