### ISSUE TITLE
 unresolved dependency in chapter-cluster

### ISSUE THREAD

**Issue by zkidkid** [RayRoestenburg/akka-in-action#81]
Hi,
I got these errors when use sbt assembly. 
I used scalaVersion=2.12 & sbtVersion=1.0
```
[error] unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.2.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-multi-jvm;0.3.11: not found
```

**Comment by RayRoestenburg** [comment]
Use sbt version 0.13.x please.

**Comment by RayRoestenburg** [comment]
(This project has not been updated to sbt 1.0, which is probably why you
are getting this error.)
