### ISSUE TITLE
A problem about function complete

### ISSUE THREAD

**Issue by ShutaoTang** [RayRoestenburg/akka-in-action#88]
For **chapter-remoting** project:

In file `RestApi.scala`

     def eventsRoute =
        pathPrefix("events") {
           pathEndOrSingleSlash {
              get {
                // GET /events
                 onSuccess(getEvents()) { events =>
                     complete(OK, events)
                 }
              }
           }
        }

The Intelj IDEA shows the error "too many argument" of function `complete(OK, events)`

Then I link to the source code of `complete`, which owns the following signature:

    def complete(m: ⇒ ToResponseMarshallable): StandardRoute =
        StandardRoute(_.complete(m))

So I would like to know how to fix it? Thanks a bunch.

**Comment by RayRoestenburg** [comment]
You can do:

 complete((OK, events))

I don't think you are getting an error, it is likely a warning. (Maybe you
are using -Xfatal-warnings)

**Comment by RayRoestenburg** [comment]
you can also just do:

```
complete(events)
```
